CREATE TABLE IF NOT EXISTS USERS
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(50)                             NOT NULL,
    email VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT UQ_USER_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation       VARCHAR(2000)                           NOT NULL,
    category_id      BIGINT REFERENCES CATEGORIES (id),
    confirmedRequest INTEGER                                 NOT NULL,
    createdOn        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description      VARCHAR(7000)                           NOT NULL,
    eventDate        TIMESTAMP                               NOT NULL,
    initiator_id     BIGINT REFERENCES USERS (id)            NOT NULL,
    lat              FLOAT                                   NOT NULL,
    lon              FLOAT                                   NOT NULL,
    paid             BOOLEAN                                 NOT NULL,
    participantLimit INTEGER,
    publishedOn      TIMESTAMP WITHOUT TIME ZONE,
    requestModerator BOOLEAN                                 NOT NULL,
    state            VARCHAR(20)                             NOT NULL,
    title            VARCHAR(200)                            NOT NULL,
    views            INTEGER,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REQUEST
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  VARCHAR(50)                             NOT NULL,
    event_id BIGINT REFERENCES EVENTS (id)           NOT NULL,
    user_id  BIGINT REFERENCES USERS (id)            NOT NULL,
    status   VARCHAR(20)                             NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPILATIONS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COMPILATIONS_EVENTS
(
    compilation_id BIGINT REFERENCES COMPILATIONS (id) NOT NULL,
    event_id       BIGINT REFERENCES EVENTS (id)       NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text_comment VARCHAR(1000)                           NOT NULL,
    event_id     BIGINT REFERENCES EVENTS (id)           NOT NULL,
    author_id    BIGINT REFERENCES USERS (id)            NOT NULL,
    created      TIMESTAMP                               NOT NULL
);
